// src/theme.ts

export const theme = {
    colors: {
      primary: 'bg-blue-600 hover:bg-blue-700 text-white',
      secondary: 'bg-gray-300 hover:bg-gray-400 text-black',
      error: 'bg-red-100 border border-red-400 text-red-700',
      success: 'bg-green-100 border border-green-400 text-green-700',
      backgroundGradient: 'bg-gradient-to-br from-gray-100 via-gray-200 to-gray-100',
      glass: 'backdrop-blur-md bg-white/80 border border-gray-200 rounded-xl',
      textPrimary: 'text-gray-800',
      textSecondary: 'text-gray-600',
      button: {
        primary: 'bg-blue-600 hover:bg-blue-700 text-white transition-all duration-200 ease-in-out transform hover:scale-105',
        secondary: 'bg-gray-300 hover:bg-gray-400 text-black transition-all duration-200 ease-in-out transform hover:scale-105',
        icon: 'w-4 h-4',
      },
      spinner: 'w-12 h-12 border-4 border-blue-500 border-t-transparent rounded-full animate-spin',
      badge: 'px-3 py-1 rounded-full bg-blue-100 border border-blue-300 text-blue-500 text-sm',
      overlay: 'fixed inset-0 bg-black/60 flex items-center justify-center z-50 p-4',
      modal: 'relative bg-white rounded-lg overflow-hidden',
      table: 'w-full',
      tableHeader: 'border-b border-gray-300',
      tableRow: 'border-b border-gray-200 hover:bg-gray-100',
    },
    buttons: {
      upload: 'flex items-center gap-2 px-6 py-3 rounded-lg',
      toggle: 'flex items-center gap-2 px-4 py-2 rounded-lg bg-gray-300 hover:bg-gray-400',
      navigation: 'p-2 rounded-full bg-black/30 backdrop-blur-sm border border-white/10 text-white/90 hover:bg-black/50 disabled:opacity-30 disabled:cursor-not-allowed transition-all',
      enlarge: 'p-2 rounded-full bg-gray-300 hover:bg-gray-400 text-gray-800 transition-all duration-200 ease-in-out',
    },
    layout: {
      container: 'min-h-screen bg-gradient-to-br from-gray-100 via-gray-200 to-gray-100 text-gray-800 py-8 px-4',
      header: 'text-center space-y-4',
      nav: 'flex space-x-4',
      glassPane: 'backdrop-blur-md bg-white/80 border border-gray-200 rounded-xl p-4',
      contentPane: 'backdrop-blur-md bg-white/80 border border-gray-200 rounded-xl p-8',
      table: 'w-full',
      tableHeader: 'border-b border-gray-300',
      tableRow: 'border-b border-gray-200 hover:bg-gray-100',
      badge: 'px-3 py-1 rounded-full bg-blue-100 border border-blue-300',
    },
    text: {
      heading1: 'text-5xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-blue-500 to-green-500',
      heading2: 'text-2xl font-semibold text-gray-800 flex items-center gap-3',
      heading3: 'text-xl font-semibold text-gray-800',
      paragraph: 'text-lg text-gray-600',
      textSecondary: 'text-gray-600',
      small: 'text-sm text-gray-600',
      modalClose: 'absolute top-2 right-2 p-2 rounded-full bg-white/80 hover:bg-white/100 transition-all',
    },
    animations: {
      fadeIn: {
        initial: { opacity: 0, y: 20 },
        animate: { opacity: 1, y: 0 },
        exit: { opacity: 0, y: -20 },
      },
      spinner: {
        initial: { opacity: 0 },
        animate: { opacity: 1 },
        transition: { duration: 0.5 },
      },
      modalScale: {
        initial: { scale: 0.8 },
        animate: { scale: 1 },
        exit: { scale: 0.8 },
        transition: { duration: 0.3 },
      },
      imageFade: {
        initial: { opacity: 0 },
        animate: { opacity: 1 },
        exit: { opacity: 0 },
        transition: { duration: 0.2 },
      },
    },
  };  